//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.CustomerResponsibleUsers = new HashSet<CustomerResponsibleUser>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int RegionId { get; set; }
        public Nullable<int> PriorityId { get; set; }
        public byte Type { get; set; }
        public double Cost { get; set; }
        public double Hours { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
    
        public virtual Priority Priority { get; set; }
        public virtual Region Region { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerResponsibleUser> CustomerResponsibleUsers { get; set; }
    }
}
